### ISSUE TITLE
HTML, CSS -> React Component (반응형 웹에 대한 수정 필요)

### ISSUE THREAD

**Issue by glitterer** [gomjellie/open-namu#7]
tablet 및 모바일 앱의 형태로 바꿨을 때, aside가 밑으로 가야 하는데,
전체 화면의 비율만 바뀌는 현상에 대한 처리가 필요합니다.

**Comment by Chan-oh** [comment]
Components 파일에 Aside.tsx 열어보면,
<main>      ==> 이게 10행에
</main>     ==> 이게 210행에 작성되어 있습니다.

210행에 있는 </main>을 114행 (113행</aside>와 115행</aside calssName="tablet_aside"> 사이 행)으로 옮겨주면 tablet 모드에서 aside가 밑으로 가 정상 작동되는 것 같아요!

**Comment by glitterer** [comment]
> Components 파일에 Aside.tsx 열어보면,
> main ==> 이게 10행에
> /main ==> 이게 210행에 작성되어 있습니다.
> 
> 210행에 있는 을 114행 (113행와 115행</aside calssName="tablet_aside"> 사이 행)으로 옮겨주면 tablet 모드에서 aside가 밑으로 가 정상 작동되는 것 같아요!

아! 저게 원래 html 파일에서도 저렇게 되어있던 거군요? 수정과정에서 </main>이 다른 곳으로 이동되었었나보네요.
